-- Migration V7: Seed official 37 document support categories in exact order

INSERT INTO clinova_db.categorias_soporte (nombre, visible) VALUES
('Acta de grado Profesional', true),
('Acta grado de Bachiller', true),
('Acta grado Titulo Especialista', true),
('Afiliación ARL', true),
('Afiliación EPS', true),
('Afiliación Pensión', true),
('Antecedentes', true),
('Caja de compensacion', true),
('Carnet vacunación', true),
('Cédula de ciudadania', true),
('Certificación Bancaria', true),
('Certificado de curso basico de reanimación cardiopulmonar', true),
('Certificado de Formación', true),
('Certificado Experiencia Laboral', true),
('Cesantias', true),
('Contrato', true),
('Convalidación', true),
('Diploma Bachiller', true),
('Exámenes Medico Ocupacional', true),
('Formato de requisitos para hoja de vida y contratación', true),
('Fundacion', true),
('Incapacidades', true),
('Libreta Militar', true),
('Paz y salvo', true),
('PESV', true),
('Póliza de responsabilidad Civil', true),
('Preaviso', true),
('Procesos disciplinarios', true),
('Resolucion expedida por Instituto depertamental de salud', true),
('RUT', true),
('Soportes contables', true),
('Tarjeta profesional', true),
('Titulo de profesional', true),
('Titulo Especialista', true),
('Vacaciones', true),
('Varios y/o anexos', true),
('Verificación Rethus', true),
('Otros Soportes', true)
ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);
